
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 27.01.2004
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace BarkodRFC
{

  // Server stub class
  public abstract class BarkodRFC : SAPServer
  {
    // Constructors
    public BarkodRFC(){}
    public BarkodRFC(string ConnectionString) :base(ConnectionString){}
    public BarkodRFC(string connectionString, SAPServerHost host) : base(connectionString, host) {}
    public BarkodRFC(string[] args) : base(args) {}
    public BarkodRFC(string[] args, SAPServerHost host) : base(args, host) {}
    public BarkodRFC(string programId, string gwhost, string sapgwxx, string codepage) 
             : base(programId, gwhost, sapgwxx, codepage) {}
    public BarkodRFC(string programId, string gwhost, string sapgwxx, string codepage, SAPServerHost host)
             : base(programId, gwhost, sapgwxx, codepage, host) {}

    
    // Generated method used as a server for the remote function module Z_DATAMAX_PRINT
    [RfcMethod(AbapName = "Z_DATAMAX_PRINT")]
    protected abstract void Z_DATAMAX_PRINT (

     [RfcParameter(AbapName = "IDENT",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 30)]
     [XmlElement("IDENT", IsNullable=false)]
     string IDENT,
     [RfcParameter(AbapName = "IP",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 15)]
     [XmlElement("IP", IsNullable=false)]
     string IP,
     [RfcParameter(AbapName = "PORT",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 5)]
     [XmlElement("PORT", IsNullable=false)]
     string PORT,
     [RfcParameter(AbapName = "PRINT_COMMANDS",RfcType=RFCTYPE.RFCTYPE_CHAR, Optional = false, Direction = RFCINOUT.IN, Length = 9999)]
     [XmlElement("PRINT_COMMANDS", IsNullable=false)]
     string PRINT_COMMANDS);

  } // Server object


} // Namespace
